spring.application.name=squareGamesApi
server.port=8181

spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.use-code-as-default-message=true

game.tictactoe.default-player-count=2
game.tictactoe.default-board-size=3

game.taquin.default-player-count=1
game.taquin.default-board-size=4

game.connect-four.default-player-count=2
game.connect-four.default-board-size=7

# connexion JDBC
spring.datasource.url=jdbc:mysql://localhost:3307/SquareGames
spring.datasource.username=user
spring.datasource.password=user

spring.jpa.hibernate.ddl-auto=create-drop

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql